### ISSUE TITLE
MN Reward

### ISSUE THREAD

**Issue by iDelphi** [absolutecrypto/absolute#3]
Hi all,
I've started a new MN, it's enable and running.
How I'll wait for first payment?

**Comment by CryptoCentric** [comment]
Hi iDelphi, the first reward depends on the number of nodes on the network. It's approximately 60-80 hours at the time of writing this. 

Thanks CC

**Comment by iDelphi** [comment]
I know CryptoCentric, I don't remember opening this thread :)
See you on Discord and Telegram and compliments for your work :)
